version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
    labels:
      - "dependencies"
      - "npm"
