version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
    labels:
      - "dependencies"
      - "pnpm"
