/**
 * CategoryNormalizer Constants
 * カテゴリ判定・検証・サニタイズに使用する定数定義
 */

export const PREFERRED_KEYWORDS: readonly string[] = [
  'マスク',
  '使い捨てマスク',
  'ボードゲーム',
  'アナログゲーム',
  'カードゲーム',
  'おもちゃ',
  'ホビー',
  'フィギュア',
  'プラモデル',
  '画材',
  '文房具',
  '文具',
  '絵具',
  'オフィス用品',
  '収納',
  'チャイルドシート',
  'ジュニアシート',
  'ベビーカー',
  '抱っこ紐',
  'おむつ',
  '紙おむつ',
  'ベビーおむつ',
  'ゲーミングチェア',
  'デスクチェア',
  'パソコンチェア',
  'オフィスチェア',
  'ワークチェア',
  'Kindle',
  'Fire',
  'Echo',
  'Alexa',
  'Ring',
  'Amazonデバイス',
  'コントローラー',
  'ゲームパッド',
  'PC用ゲームパッド',
  'ヘッドセット',
  'マウス',
  'キーボード',
  '替えブラシ',
  '電動歯ブラシ',
  '歯ブラシ',
  '口腔洗浄器',
  'シェーバー',
  'オーラルケア',
  '理美容',
  'マッサージ機',
  '健康家電',
  'ロボット',
  'ガンダム',
  '美顔器',
  '美容家電',
  'ブロック',
  'レゴ',
  'Lego',
  'ベビー',
  'マタニティ',
  'ビジネス',
  'ペット',
  '猫',
  '犬',
  'キャット',
  'ドッグ',
  'キャットフード',
  'ドッグフード',
  'ヘアケア',
  'マイク',
  'ビジネス・経済',
  'マネープラン',
  '節約・家計管理',
  '投資',
  '自己啓発',
  '実用書',
  'コミック・ラノベ',
  '暮らし・健康・子育て',
  'コンタクトレンズ',
  'カラコン',
  'キャンプ',
  'アウトドア',
  'ハンドル',
  'ハンドルコントローラー',
  'スマートフォン',
  'スマホ',
  '携帯電話',
  'SDカード',
  'メモリーカード',
  'ドッキングステーション',
  'USBハブ',
  'ウェアラブルカメラ',
  'アクションカム',
  'アクションカメラ',
  'デジタルカメラ',
  'ビデオカメラ',
  '一眼レフ',
  'ミラーレス',
  'カメラ',
  'Vlogカメラ',
  '掃除機',
  'クリーナー',
  'スチームクリーナー',
  'スチーム洗浄機',
  '洗浄機',
] as const;

export const HIGH_PRIORITY_KEYWORDS: readonly string[] = [
  'microSDカード',
  'microSD',
  'ヘアドライヤー',
  'ドライヤー',
  'カールドライヤー',
  '電動頭皮ブラシ',
  '頭皮マッサージ',
  'ヘッドスパ',
  '頭皮マッサージブラシ',
  'ヘアアイロン',
  'ヘアストレートアイロン',
  'ヘアストレートナー',
  'ヘアマルチスタイラー',
  'ヘアブラシ',
  'ヘアオイル',
  'ヘアワックス',
  'ヘアカラー',
  'シャンプー',
  'トリートメント',
  'リンス',
  '育毛',
  'トニック',
  'スカルプ',
] as const;

/**
 * 無条件で有効とみなす特定カテゴリ
 */
export const EXPLICITLY_ALLOWED_CATEGORIES: ReadonlySet<string> = new Set([
  'ドラッグストア',
  '肩こり・腰痛・筋肉痛緩和',
  '保温・保冷カップ・マグ',
  'アダプタ・充電器・ケーブル',
]);

/**
 * 部分一致で優先許可するホワイトリストカテゴリ
 */
export const WHITELIST_CATEGORIES: readonly string[] = [
  '磁気・チタン・ゲルマニウムアクセサリー',
  '周辺機器・アクセサリ',
  'キーボード・マウス・入力機器',
  '体重・体脂肪・体組成計',
  'ベビーカー',
  '草刈機・刈払機パーツ・アクセサリ',
  '育毛・養毛用トニック・エッセンス',
  'ヘアケアギフトセット',
  'ヘアケア・カラー・スタイリング',
  '寝袋・シュラフ用ピロー(枕)',
  '寝袋・ベッド・マット',
] as const;

/**
 * スマートフォン本体判定用キーワード
 */
export const PHONE_KEYWORDS: readonly string[] = [
  'スマホ',
  'スマートフォン',
  'スマートホン',
  'iphone',
  'galaxy',
  'pixel',
  'xperia',
  'aquos',
  'motorola',
  'oppo',
  'redmi',
  'poco',
  'nothing',
  '携帯電話',
  'simフリー',
  'sim free',
  'arrows',
  'zenfone',
  'honor',
  'huawei',
  'xiaomi',
  'moto',
  'y!mobile',
  'ワイモバイル',
  'android',
  'アンドロイド',
  'uq mobile',
  'uqモバイル',
  '格安スマホ',
] as const;

/**
 * シューズ・履物カテゴリ判定用正規表現とキーワード
 */
export const FOOTWEAR_CATEGORY_REGEX =
  /シューズ|スニーカー|サンダル|ブーツ|スリッポン|運動靴|パンプス|ローファー|ミュール|長靴|足袋|上履き/;

export const FOOTWEAR_KEYWORDS: readonly string[] = [
  'シューズ',
  '靴',
  'スニーカー',
  'サンダル',
  'ブーツ',
  'スリッポン',
  '運動靴',
  'パンプス',
  'ローファー',
  'ミュール',
  '長靴',
  '足袋',
  '上履き',
  'インソール',
  'シュー',
  'shoe',
  'sneaker',
  'boot',
  'sandal',
] as const;

/**
 * 猫用トイレ判定用正規表現とキーワード
 */
export const CAT_TOILET_CATEGORY_REGEX = /猫用品\s*トイレ用品|猫用トイレ/;

export const CAT_KEYWORDS: readonly string[] = [
  '猫',
  'ねこ',
  'ネコ',
  'キャット',
  'cat',
  'kitten',
  'ペット',
  'pet',
] as const;

/**
 * ヘッドホン・イヤホン救済用キーワード
 */
export const HEADPHONE_KEYWORDS: readonly string[] = [
  'イヤホン',
  'ヘッドホン',
  'ヘッドセット',
  'イヤーバッド',
  'earbuds',
  'headphones',
] as const;

/**
 * 充電器救済用キーワード
 */
export const CHARGER_KEYWORDS: readonly string[] = ['充電器', '急速充電器', 'usb充電器'] as const;

/**
 * バイク用マウント判定キーワード
 */
export const BIKE_MOUNT_KEYWORDS: readonly string[] = [
  'スマホホルダー',
  'スマートフォンホルダー',
  'スマホマウント',
  'スマートフォンマウント',
  'マウント',
  'ホルダー',
  'ステー',
  'バークランプ',
  'クランプマウント',
] as const;

/**
 * ゲームパッド判定キーワード
 */
export const GAMEPAD_KEYWORDS: readonly string[] = [
  'コントローラー',
  'ゲームパッド',
  'DualSense',
  'OCTA',
  'コマンダー',
  'パッド',
] as const;

/**
 * ハンドルコントローラー（ハンコン）判定キーワード
 */
export const WHEEL_KEYWORDS: readonly string[] = [
  'ステアリング',
  'レーシングホイール',
  'ハンコン',
  'フライトスティック',
] as const;

/**
 * テレビカテゴリ除外キーワード（テレビ部品・アクセサリ用）
 */
export const TV_EXCLUDED_KEYWORDS: readonly string[] = [
  'hdd',
  'リモコン',
  'チューナー',
  '壁掛け',
  '台',
  'スタンド',
  'パーツ',
  '部品',
  'カバー',
  'アンテナ',
  'ゲーム',
] as const;

/**
 * 構造的・一般的な除外正規表現パターン
 */
export const INVALID_PATTERNS: readonly RegExp[] = [
  /sale|off|coupon|ranking|best|week|fair|event|campaign|bauhutte|free shipping|test|multibuy|experiment/i,
  /セール|オフ(?!ィス)|クーポン|ランキング|おすすめ|ウィーク|フェア|イベント|キャンペーン/,
  /企画|向け|ほか$|など$|他(?:$|[\s、])|新商品|すべて$|特設ページ|発売日お届け|父の日/,
  /替えブラシ[_＿\s]*[sｓ]/i,
  /割引|お買い得|お買得|買得|利用シーン|あわせ買い|合わせ買い|全商品$|関連製品$|新製品$|ヤスいいね|対象商品|人気商品|レビュー評価/,
  /まとめ買い|まとめでお得|中止|hqp|紐付|新生活|入園入学/,
  /定期おトク便/,
  /ポイントアップ/,
  /^・.*・$/,
  /non\s*manga/i,
  /^kos_/i,
  /winter favorites/i,
  /高評価ブランド/,
  /今旬/,
  /サンプリング除外/,
  /おもちゃ.*column/i,
  /node\d+/i,
  /特集/,
  /新着/,
  /新規発売/,
  /予約/,
  /限定/,
  /recommendation/i,
  /eligible/i,
  /widget/i,
  /smartphones/i,
  /l\d+.*cat$/i,
  /^all /i,
  /^prime /i,
  /[【】|()（）※]/,
  /^家電$/,
  /^アクセサリ$/,
  /^アクセサリー$/,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i,
  // Block numeric-only names (e.g. "6", "100")
  /^[0-9\uff10-\uff19]+$/,
  /デジタルの日/,
  /non\s*series/i,
  /高評価/,
  /注目/,
  // Block "Name [ID]" pattern (e.g. "家電 [124048011]")
  /[^[\]]{1,200} \[\d+\]/,
  /arborist merchandising root/i,
  // Generic "Store" pages
  /(?:ストア|store)/i,
  /ブラックフライデー/i,
  /文房具・オフィス用品ヤスいいね対象/,
  /日本ヒルズ・コルゲート/i,
  /umall/i,
  /祝い|(?<!グルメ|水産加工品|魚介類|スイーツ|お菓子|調味料|スープ|ドリンク)ギフト/i,
  /brandname変更/i,
  /deal/i,
  /^hpc/i,
  /^3p\b/i,
  /\w*afc[\s\d]*under/i,
  /\w+[\s\d]*under\d+/i,
  /^\d{2}\s*ビジネス/,
  /^\d{2}\s*リビング/,
  /spring must haves/i,
  /(?:kindle|無料|[0-9０-９]+万円|円|テスト|test|マッサージャーほか健康家電|[>＞]|表示されている方限定|widget)/i,
  /(?:amazon\s*global|amazonglobal|babel|コクヨ|beauty|パントリー|本日の|特選品|cml|customers' most-loved|ソニー|9999$|ポイント還元本|書籍タイトル|free\s*shipping)/i,
  // Age ranges and price ranges
  /\d+[歳才]+～/,
  /\d+(?:,\d+)?-\d+(?:,\d+)?円/,
  /ゲージ/,
  // Machine-generated IDs (e.g. L202StorageItems02Sub, L2_02_StorageItems_02Sub)
  /l[\d\s_]+[a-z]+[\d\s_]+(?:cat|sub)/i,
  // Device and Store management pages
  /(?:kindle|fire|echo|alexa|amazon|ring).*(?:一覧|ページ|ストア|store|popup|体験|イベント)/i,
  // Brand-specific promotion/coordinated pages and brand store categories
  /(?:sony|ソニー|panasonic|パナソニック|logicool|ロジクール|elecom|エレコム).*(?:特集|一覧|プロモーション|キャンペーン|限定|コーディネート)/i,
  /(?:iris|アイリス|brother|ブラザー|nestle|ネスレ|cleansui|クリンスイ|luminous|ルミナス).*(?:特集|一覧|プロモーション|キャンペーン|限定|コーディネート)/i,
  /^(?:(?:sony|ソニー|panasonic|パナソニック|logicool|ロジクール|elecom|エレコム|sanwasupply|サンワサプライ|anker|アンカー|buffalo|バッファロー|iris|アイリスオーヤマ|アイリス|brother|ブラザー|nestle|ネスレ|cleansui|クリンスイ|luminous|ルミナス|yamazen|山善|huawei|ファーウェイ|fitbit|フィットビット)[\s\u3000]*)+(?:[-－–—:・]|ストア|store|usb|ウェブカメラ|カメラ|イヤホン|ヘッドセット|ケーブル|マウス|スマートフォン|スマートウォッチ|携帯電話|衣類|ふとん乾燥機|スマホーム|充電|テレビ|話題の|$)/i,
  /話題の/,
  /日用品・生活必需品\s*[-－–—:]/i,
  /^panasonic-ha-/i,
  /^(?:philips|フィリップス)\s*(?:理美容|美容|ビューティ)/i,
  /^おうちでヘアケア/i,
  /毎日使う水/i,
  /primeday|black\s*friday|ブラックフライデー|新生活|入園入学|父の日|母の日/i,
  /^燃料$/,
  /なるほど家電/i,
  /iswhitegloverequired/i,
  /秀和システム.*コレクション/i,
  /プロも納得/i,
  /スチールラックのすごい収納/i,
  /収納ラック.*セット/i,
  /理美容以外の本体/i,
  /ドラッグストア\s*HOTW/i,
  /第[123一二三]類医薬品/i,
  /濫用の恐れ/i,
  /その他の.*(?:書籍|本|関連)$/,
  /banner|installments|membership/i,
  /productalert|stampcard/i,
  /3m[\s_-]*aone/i,
  /cospop/i,
  /など.*お得/,
  /のサポートアイテム$/,
  /^おうちで/i,
  /野外フェス/i,
  /鈴鹿\d*耐/i,
  /で役立つ/i,
  /data\s*warehouse/i,
  /dynamic\s*selection/i,
  /ExcludeASIN/i,
  /返品不可/i,
  /お客様都合/i,
  /ラインナップ/i,
  /ガイド|guide/i,
  /\b[A-Za-z0-9]+All$/i,
  /^moto\s+/i,
  /おうちで機種変更/i,
  /cero/i,
  /c-tax/i,
  /^(?:すべて|全て)の/,
  /(?:すべて|全て)\d*$/,
  /大集合/,
  /一覧$/,
  /^pd[-_\s]/i,
  /^new to amazon$/i,
] as const;

/**
 * 完全一致ブラックリスト
 * Set で保持し O(1) での高速照合を実現
 */
export const BLACKLIST_CATEGORIES_SET: ReadonlySet<string> = new Set([
  '家電＆カメラ',
  '家電・カメラ',
  'electronics',
  'arborist merchandising root',
  'pony k',
  'babel 6-2',
  'calendar test',
  'test',
  'テスト',
  '面だし用asin',
  'hair care',
  'pbhome&kitchen9999',
  'panasonic-ha-hotairstylers',
  'umall',
  'sns acquisition test hpc asins',
  'シャープの家電がお買い得',
  'ジュニアシート 3歳頃から',
  'チャイルドシート 1歳頃から',
  'チャイルドシート 新生児から',
  'カテゴリー別',
  '卒園式・入学式の撮影テクニック',
  'yobi',
  'p&g',
  '定期おトク便',
  '介護用品・生理用品',
  '花王',
  'panasonic beauty',
  'twinbird',
  'panasonic ヘアケア',
  'パナソニック ヘアケア',
  'パナソニック ヘアードライヤー',
  'おうちでヘアケア',
  'アウトドア用品',
  'スポーツ＆アウトドア',
  'sports & outdoors',
  'ホーム・日用品',
  '日用品・生活必需品：おもちゃ',
  'featured categories',
  'omron（オムロン）',
  '電池利用商品',
  'io data',
  'logicool',
  'casio',
  'lenovo',
  'drugstore - amazonglobal',
  'pb_home&kitchen',
  '新生活ギフト',
  'ya-man',
  'others',
  'pb_beauty',
  'パントリー',
  '対象asin',
  '面出し用asin',
  'internal',
  'サンワサプライ',
  'pb_pc',
  'ベビー＆マタニティ',
  'ホーム＆キッチン',
  '食品',
  '酒のみ',
  '食品・飲料・お酒',
  '服＆ファッション小物',
  'beauty store',
  'ビューティー',
  'ビューティーストア',
  'diapers',
  'シャープ',
  'special features stores',
  'self service',
  'amazon global',
  'amazon basics',
  'amazon basic',
  'amazon store',
  'その他',
  'kindle本',
  'ジャンル別',
  'custom stores',
  'custom stores navigation',
  '無料本',
  'キャンペーン',
  'まとめ買い',
  '期間限定ポイント',
  'h&s',
  'panasonic-ha-',
  'amazonベーシック',
  'kindle popup',
  'kindle書籍 5冊購入で15%ポイント還元',
  'kindle電子書籍リーダー',
  '文房具図鑑',
  '受験対策文房具',
  'コクヨの文房具・事務用品',
  '美容・健康家電',
  '理美容・健康家電',
  '理美容家電',
  'kindle書籍',
  'kindle unlimited',
  'おせちhqp紐付用',
  'amazonglobal',
  'クリスマスギフト･コフレ',
  '日用品・生活必需品 - ビューティー',
  '日用品・生活必需品 - ペット用品',
  'スッキリ片づける・収納する',
  'カー＆バイク用品',
  '車＆バイク',
  'kindleオーナー ライブラリー',
  'kindle本 (電子書籍) まとめ買いキャンペーン',
  'kindle本 ポイントアップチャンスキャンペーン',
  'kindle本はじめての購入に使える70%offクーポン',
  'kindle events',
  'ポイントフェア',
  'まとめ買い(期間限定ポイント)',
  '冬の読書応援',
  '秋',
  '冬',
  '春',
  '夏',
  'amazon',
  'baby',
  'ベビー',
  'gt managed stores',
  'スポーツ・アウトドア',
  'sports - amazonglobal free shipping',
  'babel',
  'nonmanga_',
  'new release non manga',
  'ブランド別インテリアコーディネート',
  'piano・keyboard｜headphones',
  'ピアノ・キーボード｜ヘッドホン',
  'プライム感謝祭ポイントアップ商品',
  'home&kitchen用品ポイントアップ+1% 1',
  'ホーム&キッチン用品ポイントアップ+1% 1',
  '文具・事務用品（その他）',
  '日本ヒルズ・コルゲート199t',
  '新学期文具',
  '替えブラシs',
  '家電 本体',
  '家電 新商品',
  '理美容家電 新商品',
  '理美容家電新商品特集',
  'スキンケア他美容家電新商品',
  '白系家電特集',
  '母の日特集',
  'j-pop・日本の音楽',
  'パントリー事務用品テープ・結束具',
  'ベビー・幼児用おもちゃ',
  'ベビー家具・収納',
  'ネスレ日本',
  '本',
  '書籍',
  '和書',
  'Kindle本',
  '収納・生活雑貨',
  'タケオキクチ、コムサイズム他 ビジネスファッション・小物',
  'ゲーミングチェア＆デスク',
  '特選健康家電 オムロン、タニタ、ルルド、スライブ',
]);
