name: Biome Check

permissions:
  contents: write

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'data/**'
      - 'content/**'
      - 'static/**'
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  biome:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # zizmor: ignore[artipacked]
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1

      - name: Run Biome CI with Auto Fix
        run: biome check --write .

      - name: Commit and Push Changes
        if: success()
        run: |
          chmod +x .github/workflows/scripts/git-commit-push.sh
          ./.github/workflows/scripts/git-commit-push.sh "chore: Apply Biome auto-fixes [skip ci]" "."
